name: AmeWL
version: '${project.version}'
main: org.rij.minecraft.bukkit.ametis.AmeWL
api-version: 1.19
author: RedInJector
load: STARTUP
softdepend: [AmetisAPI]

commands:
  amewhitelist:
    description: Your description
    usage: /amewhitelist [add | remove] [player name]
    permission: AmeWL.ameWLpermission