name: AmeWL
version: '1.0-SNAPSHOT'
main: org.rij.minecraft.bukkit.ametis.AmeWL
api-version: 1.19
author: RedInJector

commands:
  amewhitelist:
    description: Your description
    usage: /amewhitelist [add | remove] [player name]
    permission: AmeWL.ameWLpermission